run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/konradasb/systemd-resolved-exporter
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: package-comments
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
  gosec:
    excludes:
      - G104 # handled via errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam
  max-same-issues: 0
  max-issues-per-linter: 0
