name: dco

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    name: DCO sign-off
    runs-on: ubuntu-latest
    steps:
      - name: Get PR commits
        id: pr-commits
        uses: tim-actions/get-pr-commits@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Signed-off-by trailers
        uses: tim-actions/dco@f2279e6e62d5a7d9115b0cb8e837b777b1b02e21
        with:
          commits: ${{ steps.pr-commits.outputs.commits }}
